schema_version: 1

package:
  name: datamanifest
  version: "1.2.0"

source:
  path: ..

build:
  noarch: python

  script:
    - pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=61
    - wheel

  run:
    - "python >=3.6"
    - boto3
    - lockfile
    - tqdm

tests:
  - python:
      imports:
        - datamanifest

about:
  homepage: https://github.com/nboley/datamanifest
  summary: Lightweight tool and python library for storing and versioning collections of bioinformatics data
  license: LicenseRef-Proprietary
